{ name = "cardano-blockfrost-provider"
, dependencies =
  [ "aeson"
  , "aff"
  , "affjax"
  , "arrays"
  , "bifunctors"
  , "bignumber"
  , "bytearrays"
  , "cardano-data-lite"
  , "cardano-provider"
  , "cardano-types"
  , "console"
  , "datetime"
  , "effect"
  , "either"
  , "exceptions"
  , "foldable-traversable"
  , "foreign-object"
  , "http-methods"
  , "js-bigints"
  , "js-date"
  , "maybe"
  , "media-types"
  , "monad-logger"
  , "newtype"
  , "node-process"
  , "numbers"
  , "ordered-collections"
  , "parallel"
  , "partial"
  , "prelude"
  , "strings"
  , "transformers"
  , "tuples"
  , "uint"
  ]
, packages = ./packages.dhall
, sources = [ "src/**/*.purs", "demo/**/*.purs" ]
}
